# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Code is Software
email: david@davidnuon.com
description: >
  a collective that advocates for holistic software and continuous integration.
logo: "/assets/images/logo.jpg"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://codeis.software" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage

name: 'Code is Software'
bio: >
  We are a collective that advocates for holistic software and continuous integration.
author_image: "/assets/images/logo.jpg"
github_username:  therealdavids

# Google Analytics
analytics_id: ""

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate
